# Generated by Django 6.0.1 on 2026-04-05 19:35

from django.db import migrations


def seed_data(apps, schema_editor):
    Joke = apps.get_model('dadjokes', 'Joke')
    Picture = apps.get_model('dadjokes', 'Picture')

    jokes = [
        {
            'text': 'Why did the scarecrow win an award? Because he was outstanding in his field.',
            'contributor': 'Assignment Seed',
        },
        {
            'text': 'I only know 25 letters of the alphabet. I do not know y.',
            'contributor': 'Assignment Seed',
        },
        {
            'text': 'What do you call cheese that is not yours? Nacho cheese.',
            'contributor': 'Assignment Seed',
        },
        {
            'text': 'Why did the math book look sad? It had too many problems.',
            'contributor': 'Assignment Seed',
        },
        {
            'text': 'How does a penguin build its house? Igloos it together.',
            'contributor': 'Assignment Seed',
        },
    ]

    pictures = [
        {
            'image_url': 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400',
            'contributor': 'Assignment Seed',
        },
        {
            'image_url': 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=400',
            'contributor': 'Assignment Seed',
        },
        {
            'image_url': 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400',
            'contributor': 'Assignment Seed',
        },
        {
            'image_url': 'https://images.unsplash.com/photo-1507149833265-60c372daea22?w=400',
            'contributor': 'Assignment Seed',
        },
        {
            'image_url': 'https://images.unsplash.com/photo-1488881688186-1c8dbe1565b6?w=400',
            'contributor': 'Assignment Seed',
        },
    ]

    for joke in jokes:
        Joke.objects.get_or_create(text=joke['text'], contributor=joke['contributor'])

    for picture in pictures:
        Picture.objects.get_or_create(
            image_url=picture['image_url'], contributor=picture['contributor']
        )


def remove_seed_data(apps, schema_editor):
    Joke = apps.get_model('dadjokes', 'Joke')
    Picture = apps.get_model('dadjokes', 'Picture')
    Joke.objects.filter(contributor='Assignment Seed').delete()
    Picture.objects.filter(contributor='Assignment Seed').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_code=remove_seed_data),
    ]
