"""Link customer records to Django auth users."""
# Generated by Django 6.0.4 on 2026-04-28 16:05

from django.db import migrations


def link_customers_to_users(apps, schema_editor):
    Customer = apps.get_model('project', 'Customer')
    User = apps.get_model('auth', 'User')
    customers = list(Customer.objects.all().order_by('id'))
    
    # Link first customer to customer1 user if it exists
    if customers:
        try:
            customer1_user = User.objects.get(username='customer1')
            customers[0].user = customer1_user
            customers[0].save()
        except User.DoesNotExist:
            pass
    
    # Create users for other customers
    customer_usernames = [
        ('liam_nguyen', 'Liam', 'Nguyen'),
        ('maya_lopez', 'Maya', 'Lopez'),
    ]
    
    for i, (username, first_name, last_name) in enumerate(customer_usernames):
        if len(customers) > i + 1:
            customer = customers[i + 1]
            if not customer.user:
                try:
                    user = User.objects.get(username=username)
                except User.DoesNotExist:
                    user = User.objects.create_user(
                        username=username,
                        first_name=first_name,
                        last_name=last_name,
                        email=customer.email if customer.email else f'{username}@example.com'
                    )
                customer.user = user
                customer.save()


def reverse_link(apps, schema_editor):
    Customer = apps.get_model('project', 'Customer')
    # Clear customer-user links but don't delete users
    for customer in Customer.objects.all():
        customer.user = None
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0003_customer_user'),
    ]

    operations = [
        migrations.RunPython(link_customers_to_users, reverse_link),
    ]
